<a href="https://colab.research.google.com/github/setyo-dwi-pratama/data-analyst/blob/master/sales2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [4]:
sales = pd.read_csv("https://raw.githubusercontent.com/setyo-dwi-pratama/data-analyst/master/sales.csv") #input file dataset sales

In [5]:
sales = pd.DataFrame(sales)

In [6]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9988 entries, 0 to 9987
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      9988 non-null   object
 1   order_date    9988 non-null   object
 2   customer_id   9988 non-null   object
 3   segment       9988 non-null   object
 4   category      9988 non-null   object
 5   sub_category  9988 non-null   object
 6   sales         9988 non-null   float64
 7   quantity      9988 non-null   int64
 8   profit        9988 non-null   float64
dtypes: float64(2), int64(1), object(6)
memory usage: 702.4+ KB

In [7]:
sales.columns

Index(['order_id', 'order_date', 'customer_id', 'segment', 'category',
       'sub_category', 'sales', 'quantity', 'profit'],
      dtype='object')

In [8]:
sales.head()

         order_id  order_date customer_id  ...     sales quantity    profit
0  CA-2016-152156  2016-11-08    CG-12520  ...  261.9600        2   41.9136
1  CA-2016-152156  2016-11-08    CG-12520  ...  731.9400        3  219.5820
2  CA-2016-138688  2016-06-12    DV-13045  ...   14.6200        2    6.8714
3  US-2015-108966  2015-10-11    SO-20335  ...  957.5775        5 -383.0310
4  US-2015-108966  2015-10-11    SO-20335  ...   22.3680        2    2.5164

[5 rows x 9 columns]

In [9]:
print(sales.order_id.unique(), "; count unique :", len(sales.order_id.unique()))
print(sales.customer_id.unique(), "; count unique :", len(sales.customer_id.unique()))
print(sales.segment.unique(), "; count unique :", len(sales.segment.unique()))
print(sales.category.unique(), "; count unique :", len(sales.category.unique()))
print(sales.sub_category.unique(), "; count unique :", len(sales.sub_category.unique()))

['CA-2016-152156' 'CA-2016-138688' 'US-2015-108966' ... 'CA-2014-110422'
 'CA-2017-121258' 'CA-2017-119914'] ; count unique : 5008
['CG-12520' 'DV-13045' 'SO-20335' 'BH-11710' 'AA-10480' 'IM-15070'
 'HP-14815' 'PK-19075' 'AG-10270' 'ZD-21925' 'KB-16585' 'SF-20065'
 'EB-13870' 'EH-13945' 'TB-21520' 'MA-17560' 'GH-14485' 'SN-20710'
 'LC-16930' 'RA-19885' 'ES-14080' 'ON-18715' 'PO-18865' 'LH-16900'
 'DP-13000' 'JM-15265' 'TB-21055' 'KM-16720' 'PS-18970' 'BS-11590'
 'KD-16270' 'HM-14980' 'JE-15745' 'KB-16600' 'SC-20770' 'DN-13690'
 'JC-16105' 'CS-12400' 'PG-18895' 'GM-14455' 'JS-15685' 'KB-16315'
 'RB-19705' 'PN-18775' 'KD-16345' 'ER-13855' 'RB-19465' 'GZ-14470'
 'LC-16870' 'JM-15250' 'PA-19060' 'CV-12805' 'CL-12565' 'RC-19960'
 'DK-13090' 'GG-14650' 'SC-20725' 'AD-10180' 'PF-19165' 'TS-21610'
 'LS-16975' 'DW-13585' 'LC-16885' 'JD-15895' 'SH-19975' 'SG-20080'
 'HA-14920' 'MG-17680' 'JE-16165' 'TW-21025' 'SP-20650' 'NK-18490'
 'DB-13060' 'NP-18670' 'TT-21070' 'EM-13960' 'RD-19900' 'MJ-17740'
 'BM-11140' 'CS-12130' 'JB-15400' 'SJ-20500' 'JK-15640' 'DK-13150'
 'RM-19675' 'SK-19990' 'FM-14290' 'AM-10360' 'MP-17470' 'MZ-17515'
 'CB-12025' 'VM-21685' 'FH-14365' 'MB-17305' 'BS-11755' 'LC-17140'
 'HK-14890' 'LE-16810' 'JH-15985' 'MS-17980' 'VW-21775' 'JH-15910'
 'JB-15925' 'DS-13180' 'VD-21670' 'EA-14035' 'DB-13120' 'KL-16645'
 'DW-13480' 'LH-17155' 'KC-16540' 'DL-13315' 'DR-12880' 'CC-12670'
 'Dl-13600' 'SB-20290' 'RC-19825' 'AH-10210' 'CB-12535' 'CA-12310'
 'KH-16690' 'BB-10990' 'AG-10495' 'JO-15280' 'AH-10195' 'NZ-18565'
 'KL-16555' 'AS-10225' 'CR-12625' 'SH-20395' 'BP-11185' 'TS-21205'
 'AG-10525' 'SP-20860' 'NM-18445' 'FA-14230' 'GK-14620' 'DJ-13510'
 'PO-18850' 'JL-15850' 'DB-13615' 'AC-10420' 'CC-12550' 'TD-20995'
 'AB-10060' 'JL-15505' 'VB-21745' 'KW-16435' 'JD-16060' 'MK-17905'
 'GT-14755' 'AG-10900' 'MM-18280' 'AR-10405' 'RA-19915' 'AS-10285'
 'LA-16780' 'DO-13435' 'DK-13225' 'NG-18430' 'MV-18190' 'JG-15115'
 'BP-11095' 'VP-21730' 'SS-20140' 'AG-10675' 'LF-17185' 'RF-19840'
 'KH-16510' 'KC-16675' 'CJ-12010' 'PB-19150' 'MP-17965' 'NF-18385'
 'SD-20485' 'KH-16630' 'RB-19795' 'MK-18160' 'PO-19180' 'BB-11545'
 'TB-21595' 'RB-19360' 'EB-13705' 'SC-20095' 'TN-21040' 'JS-15940'
 'MH-17785' 'JP-15520' 'JE-15475' 'JG-15805' 'XP-21865' 'EM-14065'
 'MT-18070' 'SA-20830' 'CW-11905' 'AJ-10960' 'SS-20590' 'RO-19780'
 'MD-17350' 'MY-17380' 'CM-12385' 'LS-17245' 'BN-11515' 'DB-13210'
 'MC-17605' 'BD-11605' 'PH-18790' 'MG-18145' 'KB-16240' 'JC-15340'
 'RL-19615' 'AA-10375' 'EP-13915' 'DK-12985' 'BD-11500' 'LM-17065'
 'AS-10135' 'BD-11320' 'GT-14710' 'AJ-10945' 'OT-18730' 'LP-17080'
 'CA-12775' 'JF-15490' 'FP-14320' 'EB-13840' 'JF-15415' 'SF-20200'
 'TG-21640' 'CS-11950' 'CC-12145' 'DV-13465' 'BD-11725' 'ZC-21910'
 'MS-17830' 'LR-16915' 'TP-21130' 'CK-12205' 'AS-10240' 'AR-10510'
 'NB-18655' 'GD-14590' 'CK-12595' 'NG-18355' 'CA-12265' 'SF-20965'
 'MO-17800' 'AT-10735' 'FM-14380' 'DJ-13420' 'ME-17725' 'JD-16150'
 'JL-15835' 'SC-20305' 'CC-12430' 'AR-10825' 'SR-20740' 'CR-12730'
 'EH-14125' 'SP-20545' 'TH-21235' 'RP-19390' 'RB-19570' 'CD-11980'
 'DJ-13630' 'GT-14635' 'MC-17845' 'RA-19285' 'NP-18325' 'AB-10165'
 'JO-15550' 'JK-15370' 'BN-11470' 'DP-13165' 'TH-21550' 'AP-10915'
 'RS-19765' 'SV-20365' 'CK-12325' 'RD-19810' 'MR-17545' 'SC-20695'
 'JF-15355' 'EG-13900' 'DS-13030' 'PO-19195' 'SS-20875' 'PB-19105'
 'RF-19735' 'YC-21895' 'DC-13285' 'CP-12340' 'BF-11020' 'LH-17020'
 'CS-12250' 'AJ-10795' 'BV-11245' 'DL-12865' 'BM-11785' 'LT-17110'
 'JK-15730' 'ES-14020' 'RH-19495' 'CD-11920' 'HW-14935' 'MC-18130'
 'GM-14440' 'PJ-19015' 'BW-11110' 'TR-21325' 'PG-18820' 'JL-15175'
 'BM-11650' 'EM-14095' 'AF-10885' 'GA-14725' 'CK-12760' 'DP-13105'
 'BK-11260' 'SJ-20125' 'CM-12445' 'AJ-10780' 'LS-16945' 'GP-14740'
 'PK-18910' 'SM-20005' 'AG-10765' 'PM-19135' 'LL-16840' 'JS-15595'
 'EL-13735' 'PC-18745' 'HL-15040' 'MS-17365' 'GB-14530' 'JR-16210'
 'BE-11335' 'SC-20050' 'RW-19630' 'SE-20110' 'AH-10075' 'JM-15535'
 'JJ-15760' 'RK-19300' 'CG-12040' 'RP-19270' 'KC-16255' 'KH-16360'
 'GH-14665' 'SW-20275' 'JA-15970' 'DL-12925' 'LW-16990' 'TB-21190'
 'BS-11800' 'RW-19690' 'TZ-21580' 'AS-10630' 'TS-21340' 'SL-20155'
 'MW-18235' 'RD-19585' 'RA-19945' 'MT-17815' 'VG-21790' 'JS-15880'
 'KM-16225' 'HR-14770' 'DE-13255' 'AG-10390' 'JJ-15445' 'JH-15430'
 'RD-19660' 'MO-17500' 'NS-18640' 'DG-13300' 'NF-18595' 'MG-17650'
 'TS-21160' 'BD-11620' 'CM-12160' 'SN-20560' 'EH-14005' 'FO-14305'
 'MS-17710' 'CC-12100' 'DW-13540' 'BT-11395' 'CY-12745' 'BT-11485'
 'PS-19045' 'PV-18985' 'NM-18520' 'DL-13495' 'CS-12355' 'FH-14275'
 'NC-18340' 'AA-10315' 'LT-16765' 'AP-10720' 'PM-18940' 'AT-10435'
 'CA-12055' 'HR-14830' 'BT-11530' 'LH-16750' 'SW-20755' 'SP-20620'
 'BF-11170' 'KT-16480' 'BG-11695' 'GM-14680' 'EJ-14155' 'NP-18700'
 'MH-18115' 'JR-15700' 'SM-20950' 'CC-12220' 'PF-19225' 'DC-12850'
 'BD-11770' 'GM-14500' 'TB-21355' 'JH-16180' 'EB-13975' 'QJ-19255'
 'TC-21535' 'CS-12460' 'HG-14965' 'LW-16825' 'MC-17575' 'LP-17095'
 'EB-14170' 'GZ-14545' 'CP-12085' 'FG-14260' 'LD-17005' 'AB-10255'
 'MN-17935' 'JR-15670' 'JF-15190' 'CM-12115' 'AS-10045' 'BP-11290'
 'ND-18370' 'LB-16735' 'KT-16465' 'HM-14860' 'AB-10600' 'SZ-20035'
 'MG-17890' 'JK-16120' 'PP-18955' 'YS-21880' 'KM-16375' 'AB-10105'
 'HA-14905' 'BT-11305' 'SV-20815' 'RW-19540' 'DK-12835' 'ST-20530'
 'MM-17920' 'PW-19030' 'SC-20440' 'TS-21085' 'MC-17425' 'ME-17320'
 'NH-18610' 'MB-18085' 'KD-16495' 'KN-16390' 'NP-18685' 'CS-12505'
 'MS-17770' 'CM-12655' 'Co-12640' 'TS-21370' 'JW-15220' 'JD-15790'
 'PC-19000' 'AR-10540' 'AI-10855' 'TB-21400' 'PL-18925' 'GH-14425'
 'MP-18175' 'JM-15655' 'CL-11890' 'DB-13270' 'IG-15085' 'BO-11425'
 'AB-10150' 'JW-16075' 'EB-13750' 'SG-20470' 'CM-12190' 'AW-10840'
 'MC-18100' 'TT-21460' 'VG-21805' 'MY-18295' 'RD-19480' 'DP-13390'
 'ML-17395' 'JC-15385' 'JG-15160' 'MC-17275' 'NW-18400' 'TB-21280'
 'BS-11380' 'HH-15010' 'CD-12280' 'TH-21100' 'MM-18055' 'NS-18505'
 'RB-19645' 'SW-20455' 'EB-13930' 'PS-18760' 'HF-14995' 'HZ-14950'
 'CD-12790' 'JK-15205' 'FM-14215' 'ED-13885' 'DA-13450' 'JW-15955'
 'RM-19375' 'ML-17755' 'CC-12685' 'JE-15610' 'RP-19855' 'TB-21175'
 'BE-11455' 'JF-15565' 'PB-19210' 'BT-11680' 'JL-15235' 'CH-12070'
 'ND-18460' 'BF-10975' 'KH-16330' 'GW-14605' 'NC-18625' 'ME-18010'
 'BP-11230' 'JC-15775' 'AS-10090' 'AC-10450' 'MD-17860' 'DB-13660'
 'EH-13990' 'EH-13765' 'SC-20230' 'JE-15715' 'AC-10615' 'JD-16015'
 'CB-12415' 'JS-16030' 'LW-17215' 'SC-20800' 'AM-10705' 'RH-19510'
 'CT-11995' 'MC-17590' 'CC-12610' 'KA-16525' 'TC-20980' 'BF-11080'
 'MM-17260' 'AH-10120' 'BW-11200' 'SW-20245' 'BS-11665' 'RF-19345'
 'WB-21850' 'TB-21625' 'AF-10870' 'RB-19435' 'KF-16285' 'JH-15820'
 'IL-15100' 'PB-18805' 'RH-19600' 'AW-10930' 'ML-17410' 'DB-13555'
 'MH-17620' 'DK-13375' 'BT-11440' 'DB-13405' 'TG-21310' 'BF-11005'
 'JM-16195' 'MZ-17335' 'MW-18220' 'MV-17485' 'SM-20320' 'TP-21415'
 'JK-15625' 'PJ-18835' 'RS-19420' 'SV-20935' 'BC-11125' 'EM-13825'
 'BM-11575' 'KN-16705' 'KW-16570' 'SC-20260' 'CV-12295' 'SG-20605'
 'TM-21010' 'EM-13810' 'ML-18040' 'CR-12580' 'AZ-10750' 'PW-19240'
 'SC-20380' 'CM-11935' 'GM-14695' 'TB-21250' 'JM-15865' 'SC-20575'
 'LS-17200' 'RR-19315' 'DB-12910' 'TT-21220' 'LO-17170' 'KD-16615'
 'NB-18580' 'BD-11635' 'CM-12235' 'EN-13780' 'KN-16450' 'BO-11350'
 'AG-10300' 'MC-17635' 'TA-21385' 'JF-15295' 'TT-21265' 'SB-20170'
 'CL-12700' 'HG-15025' 'NL-18310' 'RR-19525' 'TC-21295' 'SV-20785'
 'BE-11410' 'SC-20680' 'DF-13135' 'FH-14350' 'MS-17530' 'RH-19555'
 'GA-14515' 'JP-16135' 'Dp-13240' 'MO-17950' 'DL-13330' 'MH-18025'
 'DR-12940' 'DM-13015' 'CA-11965' 'AC-10660' 'DM-13345' 'VF-21715'
 'CC-12370' 'BF-11275' 'HG-14845' 'BP-11155' 'EM-14140' 'MA-17995'
 'AY-10555' 'GB-14575' 'JB-16045' 'MG-17875' 'SR-20425' 'JB-16000'
 'DM-12955' 'TC-21475' 'SW-20350' 'RE-19450' 'BF-11215' 'KB-16405'
 'JG-15310' 'EC-14050' 'EB-14110' 'JP-15460' 'CS-11845' 'GH-14410'
 'PT-19090' 'JL-15130' 'AH-10030' 'CC-12475' 'DW-13195' 'SJ-20215'
 'BG-11740' 'LB-16795' 'CM-11815' 'EH-14185' 'TS-21505' 'PR-18880'
 'LC-17050' 'CS-12490' 'DH-13075' 'JO-15145' 'AH-10690' 'HJ-14875'
 'MH-17455' 'RD-19930' 'SC-20020' 'SU-20665' 'FC-14335' 'RB-19330'
 'NC-18535' 'DB-12970' 'MF-17665' 'RM-19750' 'VM-21835' 'EJ-13720'
 'NC-18415' 'LS-17230' 'KE-16420' 'DH-13675' 'PF-19120' 'VT-21700'
 'MG-17695' 'SP-20920' 'CS-12175' 'DK-12895' 'KM-16660' 'AA-10645'
 'DD-13570' 'AH-10465' 'TP-21565' 'EK-13795' 'CR-12820' 'SG-20890'
 'AH-10585' 'NF-18475' 'BS-11365' 'SH-20635' 'RD-19720' 'AG-10330'
 'GR-14560' 'VS-21820' 'TM-21490' 'TS-21430' 'DB-13360' 'NR-18550'
 'CS-11860' 'MF-18250' 'LW-17125' 'AR-10345' 'KS-16300' 'AB-10015'
 'LR-17035' 'SS-20410' 'JM-15580' 'JK-15325' 'DM-13525' 'ML-18265'
 'MH-17290' 'FC-14245' 'TH-21115' 'JK-16090' 'SB-20185' 'BG-11035'
 'BW-11065' 'MG-18205' 'DO-13645' 'BP-11050' 'TS-21655' 'EM-14200'
 'AO-10810' 'MH-17440' 'SS-20515' 'LD-16855' 'VP-21760' 'TC-21145'
 'IM-15055' 'AR-10570' 'CM-12715' 'FW-14395' 'LC-16960' 'HE-14800'
 'BD-11560' 'HD-14785' 'CJ-11875' 'RS-19870' 'SC-20845' 'RE-19405'
 'SM-20905'] ; count unique : 793
['Consumer' 'Corporate' 'Home Office'] ; count unique : 3
['Furniture' 'Office Supplies' 'Technology'] ; count unique : 3
['Bookcases' 'Chairs' 'Labels' 'Tables' 'Storage' 'Furnishings' 'Art'
 'Phones' 'Binders' 'Appliances' 'Paper' 'Accessories' 'Envelopes'
 'Fasteners' 'Supplies' 'Machines' 'Copiers'] ; count unique : 17

In [10]:
sales.isnull().sum()

order_id        0
order_date      0
customer_id     0
segment         0
category        0
sub_category    0
sales           0
quantity        0
profit          0
dtype: int64

In [11]:
sales['order_date'] = pd.to_datetime(sales['order_date'])

In [12]:
sales.sort_values(by=['order_date'], ignore_index=True, inplace=True)

In [13]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9988 entries, 0 to 9987
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      9988 non-null   object
 1   order_date    9988 non-null   datetime64[ns]
 2   customer_id   9988 non-null   object
 3   segment       9988 non-null   object
 4   category      9988 non-null   object
 5   sub_category  9988 non-null   object
 6   sales         9988 non-null   float64
 7   quantity      9988 non-null   int64
 8   profit        9988 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 702.4+ KB

In [14]:
sales

            order_id order_date customer_id  ...    sales quantity   profit
0     CA-2014-103800 2014-01-03    DP-13000  ...   16.448        2   5.5512
1     CA-2014-112326 2014-01-04    PO-19195  ...    3.540        2  -5.4870
2     CA-2014-112326 2014-01-04    PO-19195  ...  272.736        3 -64.7748
3     CA-2014-112326 2014-01-04    PO-19195  ...   11.784        3   4.2717
4     CA-2014-141817 2014-01-05    MB-18085  ...   19.536        3   4.8840
...              ...        ...         ...  ...      ...      ...      ...
9983  CA-2017-115427 2017-12-30    EB-13975  ...   20.720        2   6.4750
9984  CA-2017-156720 2017-12-30    JM-15580  ...    3.024        3  -0.6048
9985  CA-2017-143259 2017-12-30    PO-18865  ...   52.776        3  19.7910
9986  CA-2017-143259 2017-12-30    PO-18865  ...   90.930        7   2.7279
9987  CA-2017-143259 2017-12-30    PO-18865  ...  323.136        4  12.1176

[9988 rows x 9 columns]

In [27]:
def data0(tah):
  hasil = pd.DataFrame()
  df = sales
  y = [2014,2015,2016,2017]
  if tah in y:
    tahun = df['order_date'].map(lambda x : x.year  == tah)
    hasil = df[tahun].reset_index(drop=True)
  else:
    print("Maaf, tidak ada data di tahun tersebut")
    print("""Pilih Tahun :
    2014
    2015
    2016
    2017""")
  return hasil

In [28]:
data0(2014)

            order_id order_date customer_id  ...     sales quantity    profit
0     CA-2014-103800 2014-01-03    DP-13000  ...    16.448        2    5.5512
1     CA-2014-112326 2014-01-04    PO-19195  ...     3.540        2   -5.4870
2     CA-2014-112326 2014-01-04    PO-19195  ...   272.736        3  -64.7748
3     CA-2014-112326 2014-01-04    PO-19195  ...    11.784        3    4.2717
4     CA-2014-141817 2014-01-05    MB-18085  ...    19.536        3    4.8840
...              ...        ...         ...  ...       ...      ...       ...
1987  US-2014-143231 2014-12-31    GM-14455  ...    63.200        5   23.3840
1988  US-2014-143231 2014-12-31    GM-14455  ...   113.970        3   27.3528
1989  CA-2014-157644 2014-12-31    AH-10030  ...    18.900        3    8.6940
1990  CA-2014-157644 2014-12-31    AH-10030  ...    34.770        3   11.4741
1991  CA-2014-150245 2014-12-31    PC-18745  ...  1573.488        7  196.6860

[1992 rows x 9 columns]

In [29]:
data0(2015)

            order_id order_date customer_id  ...     sales quantity    profit
0     CA-2015-104514 2015-01-02    CB-12535  ...    85.520        2   22.2352
1     CA-2015-146262 2015-01-02    VW-21775  ...    62.982        3  -14.6958
2     CA-2015-104514 2015-01-02    CB-12535  ...     9.840        3    2.6568
3     CA-2015-104514 2015-01-02    CB-12535  ...    20.040        3    9.6192
4     CA-2015-146262 2015-01-02    VW-21775  ...  1188.000        9 -950.4000
...              ...        ...         ...  ...       ...      ...       ...
2097  CA-2015-120901 2015-12-31    BG-11035  ...   152.688        2  -26.7204
2098  CA-2015-120901 2015-12-31    BG-11035  ...     3.488        2    0.5668
2099  CA-2015-109197 2015-12-31    JO-15280  ...   487.984        2  152.4950
2100  CA-2015-156377 2015-12-31    TB-21625  ...    14.760        5  -11.4390
2101  CA-2015-109470 2015-12-31    KC-16255  ...   364.800       12  167.8080

[2102 rows x 9 columns]

In [30]:
data0(2016)

            order_id order_date customer_id  ...     sales quantity    profit
0     CA-2016-160304 2016-01-02    BM-11575  ...   231.980        2   67.2742
1     CA-2016-160304 2016-01-02    BM-11575  ...   173.940        3   38.2668
2     CA-2016-125206 2016-01-03    LR-16915  ...   114.460        2   28.6150
3     CA-2016-105207 2016-01-03    BO-11350  ...    11.880        2    5.3460
4     CA-2016-105207 2016-01-03    BO-11350  ...  1592.850        7  350.4270
...              ...        ...         ...  ...       ...      ...       ...
2580  US-2017-165953 2016-12-31    EP-13915  ...    23.480        5    8.2180
2581  CA-2017-160395 2016-12-31    KL-16555  ...     3.640        2    1.6380
2582  CA-2017-100202 2016-12-31    BD-11620  ...   302.376        3   22.6782
2583  CA-2017-160395 2016-12-31    KL-16555  ...   159.768        7   53.9217
2584  US-2017-105830 2016-12-31    DB-13660  ...   156.512        4  -35.2152

[2585 rows x 9 columns]

In [31]:
data0(2017)

            order_id order_date customer_id  ...    sales quantity    profit
0     CA-2017-151750 2017-01-01    JM-15250  ...   15.224        2  -38.8212
1     CA-2017-144463 2017-01-01    SC-20725  ...  474.430       11  199.2606
2     CA-2017-151750 2017-01-01    JM-15250  ...  454.560        5 -107.9580
3     CA-2017-154466 2017-01-01    DP-13390  ...    3.600        2    1.7280
4     CA-2017-107503 2017-01-01    GA-14725  ...   48.896        4    8.5568
...              ...        ...         ...  ...      ...      ...       ...
3304  CA-2017-115427 2017-12-30    EB-13975  ...   20.720        2    6.4750
3305  CA-2017-156720 2017-12-30    JM-15580  ...    3.024        3   -0.6048
3306  CA-2017-143259 2017-12-30    PO-18865  ...   52.776        3   19.7910
3307  CA-2017-143259 2017-12-30    PO-18865  ...   90.930        7    2.7279
3308  CA-2017-143259 2017-12-30    PO-18865  ...  323.136        4   12.1176

[3309 rows x 9 columns]

In [32]:
data0(2019)

Maaf, tidak ada data di tahun tersebut
Pilih Tahun :
    2014
    2015
    2016
    2017

Empty DataFrame
Columns: []
Index: []

In [58]:
def data1(tah,bul):
  hasil = pd.DataFrame()
  df = sales
  y = [2014,2015,2016,2017]
  m = [1,2,3,4,5,6,7,8,9,10,11,12]
  if tah in y and bul in m:
    tahun = df['order_date'].map(lambda x : x.year  == tah)
    bulan = df['order_date'].map(lambda x : x.month  == bul)
    hasil = df[tahun & bulan].reset_index(drop=True)
  else:
    print("Maaf, tidak ada data ditahun dan bulan tersebut")
    print("""Pilih Tahun :
    2014
    2015
    2016
    2017""")
    print("""Pilih Bulan :
    1 : Januari
    2 : Februari
    3 : Maret
    4 : April
    5 : Mei
    6 : Bulannya Setyo nah
    7 : Juli
    8 : Agustus
    9 : September
    10 : Oktober
    11 : November
    12 : Desember""")
  return hasil

In [36]:
sales.segment.unique()

array(['Consumer', 'Home Office', 'Corporate'], dtype=object)

In [78]:
def data2(tah, bul, seg):
  hasil = pd.DataFrame()
  df = data1(tah, bul)
  teks = str(seg)
  seg_unique = ["Consumer","Home Office","Corporate"]
  if seg in seg_unique:
    segment1 = df[df['segment'] == teks]
    hasil = segment1.reset_index(drop=True) 
  else:
    print("Maaf Anda Salah Input Data")
  return hasil

In [84]:
data2(2014,1,'Consumer')

          order_id order_date customer_id  ...     sales quantity    profit
0   CA-2014-103800 2014-01-03    DP-13000  ...    16.448        2    5.5512
1   CA-2014-141817 2014-01-05    MB-18085  ...    19.536        3    4.8840
2   CA-2014-130813 2014-01-06    LS-17230  ...    19.440        3    9.3312
3   CA-2014-105417 2014-01-07    VS-21820  ...    10.430        7  -18.2525
4   CA-2014-105417 2014-01-07    VS-21820  ...    76.728        3  -53.7096
5   CA-2014-135405 2014-01-09    MS-17830  ...     9.344        2    1.1680
6   CA-2014-135405 2014-01-09    MS-17830  ...    31.200        3    9.7500
7   CA-2014-130092 2014-01-11    SV-20365  ...     9.940        2    3.0814
8   CA-2014-118192 2014-01-13    MM-17920  ...     3.438        2   -2.5212
9   CA-2014-118192 2014-01-13    MM-17920  ...    37.408        7   13.0928
10  CA-2014-157147 2014-01-13    BD-11605  ...  1325.850        5  238.6530
11  CA-2014-157147 2014-01-13    BD-11605  ...   333.999        3    3.9294
12  CA-2014-157147 2014-01-13    BD-11605  ...    19.900        5    6.5670
13  CA-2014-109232 2014-01-13    ND-18370  ...   545.940        6   87.3504
14  CA-2014-103366 2014-01-15    EH-13990  ...   149.950        5   65.9780
15  CA-2014-115791 2014-01-16    DL-13315  ...    30.072        3   10.1493
16  CA-2014-115791 2014-01-16    DL-13315  ...    18.588        2  -13.6312
17  CA-2014-115791 2014-01-16    DL-13315  ...   124.200        3  -31.0500
18  CA-2014-115791 2014-01-16    DL-13315  ...   127.104        6   28.5984
19  CA-2014-146591 2014-01-19    TS-21340  ...    32.340       10  -23.7160
20  CA-2014-146591 2014-01-19    TS-21340  ...    56.064        4   19.6224
21  CA-2014-146591 2014-01-19    TS-21340  ...   108.720        5   36.6930
22  CA-2014-146591 2014-01-19    TS-21340  ...   181.470        5 -320.5970
23  US-2014-147627 2014-01-20    HL-15040  ...    23.340        3   10.9698
24  CA-2014-148614 2014-01-20    MV-17485  ...    19.360        2    9.2928
25  US-2014-147627 2014-01-20    HL-15040  ...     6.630        3    1.7901
26  US-2014-147627 2014-01-20    HL-15040  ...    38.600        4   11.5800
27  US-2014-147627 2014-01-20    HL-15040  ...    22.960        7    6.6584
28  CA-2014-167927 2014-01-20    XP-21865  ...    19.050        5    8.9535
29  CA-2014-148614 2014-01-20    MV-17485  ...    19.300        2    5.7900
30  US-2014-147627 2014-01-20    HL-15040  ...   699.930        7  181.9818
31  CA-2014-167927 2014-01-20    XP-21865  ...    66.580        2   15.9792
32  US-2014-147627 2014-01-20    HL-15040  ...  1067.940        3  224.2674
33  CA-2014-167927 2014-01-20    XP-21865  ...   247.716        4   93.5816
34  CA-2014-167927 2014-01-20    XP-21865  ...    43.920        3   12.7368
35  CA-2014-167927 2014-01-20    XP-21865  ...    14.730        3    4.8609
36  CA-2014-167927 2014-01-20    XP-21865  ...    29.700        5   13.3650
37  CA-2014-167927 2014-01-20    XP-21865  ...    13.980        1    4.0542
38  CA-2014-167927 2014-01-20    XP-21865  ...   272.940        3   30.0234
39  CA-2014-110422 2014-01-21    TB-21400  ...    25.248        3    4.1028
40  CA-2014-102645 2014-01-23    IM-15055  ...    40.080        6   19.2384
41  CA-2014-146997 2014-01-23    SG-20605  ...     5.940        3    0.0000
42  US-2014-117163 2014-01-27    EJ-13720  ...   333.000        3  -16.6500
43  US-2014-117163 2014-01-27    EJ-13720  ...    57.230        1   14.3075
44  US-2014-117163 2014-01-27    EJ-13720  ...    36.440        4   12.0252
45  CA-2014-100328 2014-01-28    JC-15340  ...     3.928        1    1.3257
46  CA-2014-134103 2014-01-30    MV-18190  ...    10.560        2    4.7520
47  CA-2014-134103 2014-01-30    MV-18190  ...   229.940        2    6.8982
48  CA-2014-115161 2014-01-31    LC-17050  ...   290.666        2    3.4196

[49 rows x 9 columns]

In [104]:
def data3(tah, bul, seg):
  df = data1(tah, bul)
  teks = str(seg)
  seg_unique = ["Consumer","Home Office","Corporate"]
  if seg in seg_unique:
    segment1 = df[df['segment'] == teks]
    hasil = segment1.reset_index(drop=True)
    print("customer_id_count :", len(hasil['customer_id'].unique()))
    print("quantity_sum :", hasil['quantity'].sum())
    print("sales_sum :", hasil['sales'].sum())
    print("profit_sum :", hasil['profit'].sum())
  else:
    print("Maaf Anda Salah Input Data")

In [111]:
data3(2014, 1, 'Consumer')

customer_id_count : 22
quantity_sum : 180
sales_sum : 6927.817
profit_sum : 766.2263

In [106]:
data3(2014,2, 'Consumer')

customer_id_count : 15
quantity_sum : 95
sales_sum : 3167.854
profit_sum : 496.8669

In [107]:
data3(2014,3, 'Consumer')

customer_id_count : 38
quantity_sum : 296
sales_sum : 11869.304
profit_sum : 597.2773

In [108]:
data3(2014,4, 'Consumer')

customer_id_count : 23
quantity_sum : 184
sales_sum : 9108.612000000001
profit_sum : 1155.0756999999999

In [112]:
print(184+296+95+180)

755